Repository boostcampwm-2024/web07-Ask-It, pull requests merged in 2024-11, with the labels that each got.

#4 chore: initialize project
  .gitignore
  apps/client/.gitignore
  apps/client/README.md
  apps/client/eslint.config.js
  apps/client/index.html
  apps/client/package.json
  apps/client/public/vite.svg
  apps/client/src/App.css
  apps/client/src/App.tsx
  apps/client/src/assets/react.svg
  apps/client/src/index.css
  apps/client/src/main.tsx
  apps/client/src/vite-env.d.ts
  apps/client/tsconfig.app.json
  apps/client/tsconfig.json
  apps/client/tsconfig.node.json
  apps/client/vite.config.ts
  apps/server/.eslintrc.js
  apps/server/.gitignore
  apps/server/.prettierrc
  apps/server/README.md
  apps/server/nest-cli.json
  apps/server/package.json
  apps/server/pnpm-lock.yaml
  apps/server/src/app.controller.spec.ts
  apps/server/src/app.controller.ts
  apps/server/src/app.module.ts
  apps/server/src/app.service.ts
  apps/server/src/main.ts
  apps/server/test/app.e2e-spec.ts
  apps/server/test/jest-e2e.json
  apps/server/tsconfig.build.json
  apps/server/tsconfig.json
  package-lock.json
  package.json
Labels: CONFIGURATION

#7 chore: configure linter
  .gitignore
  apps/server/.eslintrc.js
  apps/server/.prettierrc
  apps/server/package.json
  apps/server/pnpm-lock.yaml
  apps/server/src/app.controller.spec.ts
  apps/server/src/app.controller.ts
  apps/server/src/app.module.ts
  apps/server/src/main.ts
  apps/server/test/app.e2e-spec.ts
  package-lock.json
  package.json
  pnpm-lock.yaml
Labels: Configuration

#12 chore: front-end project setup with required dependency
  .gitignore
  apps/client/.eslintrc.json
  apps/client/.prettierrc
  apps/client/eslint.config.js
  apps/client/package.json
  apps/client/pnpm-lock.yaml
  apps/client/postcss.config.js
  apps/client/public/vite.svg
  apps/client/src/App.css
  apps/client/src/App.tsx
  apps/client/src/assets/react.svg
  apps/client/src/index.css
  apps/client/src/main.tsx
  apps/client/tailwind.config.js
  apps/client/tsconfig.app.json
  apps/client/vite.config.ts
  pnpm-lock.yaml
  pnpm-workspace.yaml
Labels: Configuration

#20 chore: add linting and formatting workflows
  .github/workflows/lint-format.yml
  .gitignore
  apps/client/README.md
  apps/client/eslint.config.js
  apps/client/package.json
  apps/client/src/App.tsx
  apps/client/src/main.tsx
  apps/client/vite.config.ts
  pnpm-lock.yaml
  pnpm-workspace.yaml
  turbo.json
Labels: Configuration

#26 feat(fe): add modal management context and custom hook
  .github/workflows/lint-format.yml
  apps/client/src/features/modal/components/Background.tsx
  apps/client/src/features/modal/index.ts
  apps/client/src/features/modal/modal.context.ts
  apps/client/src/features/modal/modal.hook.tsx
Labels: Feature

#30 chore: setup CI/CD
  .github/workflows/deploy.yml
  pnpm-lock.yaml
Labels: Configuration

#28 feat(fe): add chat and Q&A management slices with session store
  apps/client/src/features/session/chatting/chatting.slice.ts
  apps/client/src/features/session/chatting/chatting.type.ts
  apps/client/src/features/session/chatting/index.ts
  apps/client/src/features/session/index.ts
  apps/client/src/features/session/qa/index.ts
  apps/client/src/features/session/qa/qa.slice.ts
  apps/client/src/features/session/qa/qa.type.ts
  apps/client/src/features/session/session.slice.ts
  apps/client/src/features/session/session.store.ts
  apps/client/src/features/session/session.type.ts
Labels: Feature

#32 fix(fe): update import path for Session type in QA module
  apps/client/src/features/session/qa/qa.type.ts
Labels: Fix

#33 fix: modify CI/CD script
  .github/workflows/deploy.yml
Labels: Bug

#31 feat(be): user registration
  apps/server/package.json
  apps/server/prisma/schema.prisma
  apps/server/src/app.controller.spec.ts
  apps/server/src/app.controller.ts
  apps/server/src/app.module.ts
  apps/server/src/app.service.ts
  apps/server/src/filters/prisma-exception.filter.ts
  apps/server/src/filters/validation-exception.filter.ts
  apps/server/src/main.ts
  apps/server/src/prisma/prisma.module.ts
  apps/server/src/prisma/prisma.service.ts
  apps/server/src/users/dto/create-user.dto.ts
  apps/server/src/users/dto/validate-user.dto.ts
  apps/server/src/users/users.controller.spec.ts
  apps/server/src/users/users.controller.ts
  apps/server/src/users/users.module.ts
  apps/server/src/users/users.repository.ts
  apps/server/src/users/users.service.spec.ts
  apps/server/src/users/users.service.ts
  pnpm-lock.yaml
Labels: Feature

#35 fix: modify CI/CD
  .github/workflows/deploy.yml
Labels: Bug, Fix

#36 fix: fix CD script
  .github/workflows/deploy.yml
Labels: Fix

#39 refactor: remove develop branches from PR workflow
  .github/workflows/lint-format.yml
Labels: Refactor

#40 fix: add pnpx prisma generate
  .github/workflows/deploy.yml
Labels: Fix

#43 feat(be): swagger setting
  apps/server/package.json
  apps/server/src/main.ts
  apps/server/src/users/dto/create-user.dto.ts
  apps/server/src/users/dto/validate-user.dto.ts
  apps/server/src/users/swagger/check-duplication.swagger.ts
  apps/server/src/users/swagger/create-user.swagger.ts
  apps/server/src/users/users.controller.ts
  pnpm-lock.yaml
  prisma/schema.prisma
Labels: Feature

#46 chore: update swagger setting
  apps/server/src/main.ts
  apps/server/src/users/swagger/check-duplication.swagger.ts
  apps/server/src/users/swagger/create-user.swagger.ts
Labels: Fix

#47 fix: add pnpm build
  .github/workflows/deploy.yml
Labels: Release, Fix

#49 feat(@fe): add signup, login, session creation modal
  .gitignore
  apps/client/.eslintrc.json
  apps/client/package.json
  apps/client/src/components/Button.tsx
  apps/client/src/components/Header.tsx
  apps/client/src/components/common/Header.tsx
  apps/client/src/components/index.ts
  apps/client/src/components/modal/CreateSessionModal.tsx
  apps/client/src/components/modal/InputField.tsx
  apps/client/src/components/modal/Modal.tsx
  apps/client/src/components/modal/SignInModal.tsx
  apps/client/src/components/modal/SignUpModal.tsx
  apps/client/src/features/modal/components/Background.tsx
  apps/client/src/features/modal/modal.hook.tsx
  apps/client/src/features/session/index.ts
  apps/client/src/features/session/session.hook.ts
  apps/client/src/pages/Home.tsx
  apps/client/vite.config.ts
  package-lock.json
  pnpm-lock.yaml
Labels: Feature

#54 refactor(be): standardize API response format and error handling
  apps/server/src/common/exceptions/base.exception.ts
  apps/server/src/common/exceptions/resource.exception.ts
  apps/server/src/common/filters/domain-exception.filter.ts
  apps/server/src/common/filters/validation-exception.filter.ts
  apps/server/src/common/interceptors/transform.interceptor.ts
  apps/server/src/filters/prisma-exception.filter.ts
  apps/server/src/main.ts
  apps/server/src/prisma/prisma.error.ts
  apps/server/src/sessions/sessions.controller.ts
  apps/server/src/sessions/sessions.repository.ts
  apps/server/src/users/exceptions/user.exception.ts
  apps/server/src/users/users.controller.ts
  apps/server/src/users/users.repository.ts
  prisma/schema.prisma
Labels: Refactor

#52 fix(fe): resolve font unapplied issue
  apps/client/src/components/FeatureCard.tsx
  apps/client/src/components/Header.tsx
  apps/client/src/components/modal/CreateSessionModal.tsx
  apps/client/src/components/modal/InputField.tsx
  apps/client/src/components/modal/SignInModal.tsx
  apps/client/src/components/modal/SignUpModal.tsx
  apps/client/src/index.css
  apps/client/src/pages/Home.tsx
  apps/client/tailwind.config.js
Labels: Fix

#50 Feat(be): user session token
  apps/server/package.json
  apps/server/prisma/migrations/20241109165716_init/migration.sql
  apps/server/prisma/migrations/20241109170330_init/migration.sql
  apps/server/prisma/migrations/20241109170857_init/migration.sql
  apps/server/prisma/migrations/20241109181624_init/migration.sql
  apps/server/prisma/migrations/20241110141915_init/migration.sql
  apps/server/prisma/migrations/20241110152007_init/migration.sql
  apps/server/prisma/migrations/20241110160147_init/migration.sql
  apps/server/prisma/migrations/20241110160251_init/migration.sql
  apps/server/prisma/migrations/20241110160419_init/migration.sql
  apps/server/prisma/schema.prisma
  apps/server/src/app.module.ts
  apps/server/src/sessions-auth/dto/session-auth.dto.ts
  apps/server/src/sessions-auth/sessions-auth.controller.spec.ts
  apps/server/src/sessions-auth/sessions-auth.controller.ts
  apps/server/src/sessions-auth/sessions-auth.module.ts
  apps/server/src/sessions-auth/sessions-auth.repository.ts
  apps/server/src/sessions-auth/sessions-auth.service.spec.ts
  apps/server/src/sessions-auth/sessions-auth.service.ts
  apps/server/src/sessions-auth/swagger/sessions-auth.swagger.ts
  apps/server/src/sessions/sessions.service.ts
  pnpm-lock.yaml
Labels: Feature

#57 feat(be): add prisma model
  apps/server/prisma/migrations/20241111022352_init/migration.sql
  apps/server/prisma/schema.prisma
Labels: Feature

#61 feat(be): add prisma model relation
  apps/server/prisma/migrations/20241111063729_init/migration.sql
  apps/server/prisma/schema.prisma
Labels: Feature

#62 refactor(be): split validation api and update swagger documentation
  apps/server/src/users/dto/create-user.dto.ts
  apps/server/src/users/dto/validate-user.dto.ts
  apps/server/src/users/swagger/check-duplication.swagger.ts
  apps/server/src/users/swagger/create-user.swagger.ts
  apps/server/src/users/users.controller.ts
  apps/server/src/users/users.service.ts
Labels: Refactor

#63 feat(fe): add Q&A page
  apps/client/.eslintrc.json
  apps/client/src/App.tsx
  apps/client/src/components/index.ts
  apps/client/src/components/qna/ChattingList.tsx
  apps/client/src/components/qna/ChattingMessage.tsx
  apps/client/src/components/qna/Question.tsx
  apps/client/src/components/qna/QuestionContent.tsx
  apps/client/src/components/qna/QuestionDetail.tsx
  apps/client/src/components/qna/QuestionList.tsx
  apps/client/src/components/qna/Reply.tsx
  apps/client/src/features/session/qa/index.ts
  apps/client/src/features/session/qna/index.ts
  apps/client/src/features/session/qna/qna.context.tsx
  apps/client/src/features/session/qna/qna.hook.ts
  apps/client/src/features/session/qna/qna.slice.ts
  apps/client/src/features/session/qna/qna.type.ts
  apps/client/src/features/session/session.slice.ts
  apps/client/src/features/session/session.store.ts
  apps/client/src/main.tsx
  apps/client/src/pages/QnA.tsx
  apps/client/src/routeTree.gen.ts
  apps/client/src/routes/__root.tsx
  apps/client/src/routes/index.tsx
  apps/client/src/routes/session.$sessionId.tsx
Labels: Feature

#65 fix(fe): resolve layout issue
  apps/client/package.json
  apps/client/src/components/qna/QuestionList.tsx
  apps/client/src/pages/Home.tsx
Labels: Fix

#67 feat(fe): implement user registration and validation features
  .github/workflows/deploy.yml
  apps/client/.gitignore
  apps/client/package.json
  apps/client/src/components/modal/InputField.tsx
  apps/client/src/components/modal/SignInModal.tsx
  apps/client/src/components/modal/SignUpModal.tsx
  apps/client/src/features/auth/auth.api.ts
  apps/client/src/features/auth/auth.dto.ts
  apps/client/src/features/auth/auth.hook.ts
  apps/client/src/features/auth/index.ts
  apps/client/src/features/session/index.ts
  apps/client/src/features/session/session.hook.ts
  apps/client/src/shared/base.dto.ts
  apps/client/src/shared/index.ts
  apps/client/src/vite-env.d.ts
  pnpm-lock.yaml
Labels: Feature

#69 feat(be): add create question and read questions api
  apps/server/prisma/migrations/20241110160251_init/migration.sql
  apps/server/src/app.module.ts
  apps/server/src/questions/dto/create-question.dto.ts
  apps/server/src/questions/dto/get-question.dto.ts
  apps/server/src/questions/questions.controller.spec.ts
  apps/server/src/questions/questions.controller.ts
  apps/server/src/questions/questions.module.ts
  apps/server/src/questions/questions.repository.ts
  apps/server/src/questions/questions.service.spec.ts
  apps/server/src/questions/questions.service.ts
  apps/server/src/questions/swagger/create-question.swagger.ts
  apps/server/src/questions/swagger/get-question.swagger.ts
Labels: Feature

#70 feat(fe): enhance validation logic
  apps/client/src/components/modal/InputField.tsx
  apps/client/src/components/modal/SignInModal.tsx
  apps/client/src/components/modal/SignUpModal.tsx
  apps/client/src/features/auth/auth.hook.ts
Labels: Feature

#77 feat(fe): update Vite config for proxy settings
  apps/client/src/features/auth/auth.api.ts
  apps/client/vite.config.ts
Labels: Feature

#85 fix(be): fix login swagger
  apps/server/src/auth/swagger/login.swagger.ts
Labels: Fix

#88 feat(fe): implement user authentication and refactor related components
  apps/client/index.html
  apps/client/src/components/Header.tsx
  apps/client/src/components/index.ts
  apps/client/src/components/modal/InputField.tsx
  apps/client/src/components/modal/SignInModal.tsx
  apps/client/src/components/modal/SignUpModal.tsx
  apps/client/src/components/my/SessionRecord.tsx
  apps/client/src/features/auth/auth.api.ts
  apps/client/src/features/auth/auth.dto.ts
  apps/client/src/features/auth/auth.hook.ts
  apps/client/src/features/auth/auth.store.ts
  apps/client/src/features/auth/index.ts
  apps/client/src/features/user/index.ts
  apps/client/src/features/user/user.api.ts
  apps/client/src/features/user/user.dto.ts
  apps/client/src/features/user/user.hook.ts
  apps/client/src/main.tsx
  apps/client/src/pages/HomePage.tsx
  apps/client/src/shared/axios.config.ts
  apps/client/src/shared/base.dto.ts
  apps/client/src/shared/date.util.ts
  apps/client/src/shared/index.ts
  apps/client/src/shared/validation/index.ts
  apps/client/src/shared/validation/validation-status.type.ts
  apps/client/src/shared/validation/validation-status.util.ts
Labels: Feature

#87 feat(be): add guards, question update api and question delete api
  apps/server/.eslintrc.js
  apps/server/.prettierrc
  apps/server/src/app.module.ts
  apps/server/src/auth/auth.service.ts
  apps/server/src/auth/swagger/login.swagger.ts
  apps/server/src/common/base.dto.ts
  apps/server/src/common/guards/session-token-validation.guard.ts
  apps/server/src/common/guards/session-token.module.ts
  apps/server/src/common/interceptors/jwt-payload.interceptor.ts
  apps/server/src/main.ts
  apps/server/src/questions/dto/create-question.dto.ts
  apps/server/src/questions/dto/update-question.dto.ts
  apps/server/src/questions/guards/question-existence.guard.ts
  apps/server/src/questions/guards/question-ownership.guard.ts
  apps/server/src/questions/questions.controller.ts
  apps/server/src/questions/questions.module.ts
  apps/server/src/questions/questions.repository.ts
  apps/server/src/questions/questions.service.ts
  apps/server/src/questions/swagger/create-question.swagger.ts
  apps/server/src/questions/swagger/delete-question.swagger.ts
  apps/server/src/questions/swagger/update-question.swagger.ts
  apps/server/src/sessions-auth/sessions-auth.controller.spec.ts
  apps/server/src/sessions-auth/sessions-auth.repository.ts
  apps/server/src/sessions-auth/sessions-auth.service.spec.ts
  apps/server/src/sessions/sessions.controller.spec.ts
  apps/server/src/sessions/sessions.repository.ts
  apps/server/src/sessions/sessions.service.spec.ts
  apps/server/src/users/users.controller.spec.ts
  apps/server/src/users/users.repository.ts
  apps/server/src/users/users.service.spec.ts
  apps/server/tsconfig.json
Labels: Feature, Refactor

#89 fix(fe): resolve build error
  apps/client/src/components/index.ts
Labels: Fix

#90 fix(fe): propagate error in useSignInForm hook
  apps/client/src/features/auth/auth.hook.ts
Labels: Fix

#91 feat(fe): add onKeyDown prop to InputField and handle Enter key in SignInModal
  apps/client/src/components/modal/InputField.tsx
  apps/client/src/components/modal/SignInModal.tsx
Labels: Feature

#86 feat(be): toggle question like
  apps/server/src/auth/auth.controller.spec.ts
  apps/server/src/auth/auth.service.spec.ts
  apps/server/src/common/interceptors/jwt-payload.interceptor.ts
  apps/server/src/prisma/prisma.error.ts
  apps/server/src/questions/dto/toggle-question-like.dto.ts
  apps/server/src/questions/questions.controller.spec.ts
  apps/server/src/questions/questions.controller.ts
  apps/server/src/questions/questions.repository.ts
  apps/server/src/questions/questions.service.spec.ts
  apps/server/src/questions/questions.service.ts
  apps/server/src/questions/swagger/toggle-question.swagger.ts
  apps/server/src/replies/dto/toggle-reply-like.dto.ts
  apps/server/src/replies/replies.controller.spec.ts
  apps/server/src/replies/replies.controller.ts
  apps/server/src/replies/replies.module.ts
  apps/server/src/replies/replies.repository.ts
  apps/server/src/replies/replies.service.spec.ts
  apps/server/src/replies/replies.service.ts
  apps/server/src/replies/swagger/toggle-reply.swagger.ts
  apps/server/src/sessions-auth/sessions-auth.controller.ts
Labels: Feature

#92 refactor(be): question like validation
  apps/server/src/questions/guards/question-existence.guard.ts
  apps/server/src/questions/questions.controller.ts
  apps/server/src/questions/questions.repository.ts
Labels: Refactor

#94 fix(be): fix validation logic
  apps/server/src/common/guards/session-token-validation.guard.ts
Labels: Fix

#96 fix(fe): disable login button when not allowed
  apps/client/src/components/modal/SignInModal.tsx
  apps/client/src/components/modal/SignUpModal.tsx
  apps/client/src/features/user/user.hook.ts
Labels: Fix

#99 feat(be): implement mypage api
  apps/server/src/questions/dto/update-question.dto.ts
  apps/server/src/sessions/sessions.controller.ts
  apps/server/src/sessions/sessions.repository.ts
  apps/server/src/sessions/sessions.service.ts
  apps/server/src/sessions/swagger/get-session.swagger.ts
Labels: Feature

#101 feat(be): implement mypage
  apps/server/src/sessions/sessions.controller.ts
  apps/server/src/sessions/sessions.repository.ts
  apps/server/src/sessions/sessions.service.ts
  apps/server/src/sessions/swagger/get-session.swagger.ts
Labels: Feature

#102 refactor(be): apply base dto
  apps/server/src/replies/dto/create-reply.dto.ts
  apps/server/src/replies/dto/delete-reply.dto.ts
  apps/server/src/replies/dto/update-reply.dto.ts
  apps/server/src/sessions/sessions.service.ts
Labels: Refactor

#104 feat(fe): add toast notification system for user feedback
  apps/client/src/components/Header.tsx
  apps/client/src/components/modal/SignInModal.tsx
  apps/client/src/components/modal/SignUpModal.tsx
  apps/client/src/features/modal/Background.tsx
  apps/client/src/features/modal/modal.hook.tsx
  apps/client/src/features/toast/ToastContainer.tsx
  apps/client/src/features/toast/ToastMessage.tsx
  apps/client/src/features/toast/index.ts
  apps/client/src/features/toast/toast.store.ts
  apps/client/src/features/toast/toast.type.ts
  apps/client/src/routes/__root.tsx
  apps/client/tailwind.config.js
Labels: Feature

#106 fix(fe): adjust modal height for CreateQuestionModal and CreateReplyModal
  apps/client/src/components/modal/CreateQuestionModal.tsx
  apps/client/src/components/modal/CreateReplyModal.tsx
Labels: Fix

#108 feat(be): implement image upload API with S3 storage support
  .github/workflows/deploy.yml
  apps/server/package.json
  apps/server/src/app.module.ts
  apps/server/src/upload/swagger/upload-image.swagger.ts
  apps/server/src/upload/upload.controller.ts
  apps/server/src/upload/upload.module.ts
  apps/server/src/upload/upload.service.ts
  apps/server/tsconfig.json
  pnpm-lock.yaml
Labels: Feature

#107 feat(be): verify reply host
  apps/server/src/replies/replies.controller.ts
  apps/server/src/replies/replies.module.ts
  apps/server/src/replies/replies.service.ts
  apps/server/src/replies/swagger/create-reply.swagger.ts
  apps/server/src/sessions-auth/sessions-auth.repository.ts
  apps/server/src/sessions/sessions.module.ts
  apps/server/src/sessions/sessions.repository.ts
  apps/server/src/sessions/sessions.service.ts
Labels: Feature

#110 feat(be): reply auth
  apps/server/src/questions/guards/question-existence.guard.ts
  apps/server/src/questions/questions.module.ts
  apps/server/src/questions/questions.repository.ts
  apps/server/src/questions/questions.service.ts
  apps/server/src/replies/guards/reply-existence.guard.ts
  apps/server/src/replies/guards/reply-ownership.guard.ts
  apps/server/src/replies/replies.controller.ts
  apps/server/src/replies/replies.repository.ts
  apps/server/src/replies/replies.service.ts
  apps/server/src/sessions-auth/sessions-auth.repository.ts
  pnpm-lock.yaml
Labels: Feature

#114 fix(be): return only the token from new user session creation
  apps/server/src/sessions-auth/sessions-auth.repository.ts
Labels: Fix

#112 feat(fe): integrate session API
  apps/client/.eslintrc.json
  apps/client/src/components/Header.tsx
  apps/client/src/components/modal/CreateSessionModal.tsx
  apps/client/src/components/my/SessionRecord.tsx
  apps/client/src/features/auth/auth.store.ts
  apps/client/src/features/session/index.ts
  apps/client/src/features/session/session.api.ts
  apps/client/src/features/session/session.dto.ts
  apps/client/src/pages/MyPage.tsx
  apps/client/src/routes/__root.tsx
  apps/client/src/routes/my.tsx
  apps/client/src/routes/session.$sessionId.tsx
Labels: Feature

#115 refactor(be): refactor convention
  apps/server/src/app.module.ts
  apps/server/src/auth/auth.controller.ts
  apps/server/src/auth/auth.module.ts
  apps/server/src/auth/auth.service.ts
  apps/server/src/auth/swagger/login.swagger.ts
  apps/server/src/common/filters/http-exception.filter.ts
  apps/server/src/common/interceptors/transform.interceptor.ts
  apps/server/src/questions/questions.repository.ts
  apps/server/src/questions/swagger/create-question.swagger.ts
  apps/server/src/questions/swagger/delete-question.swagger.ts
  apps/server/src/questions/swagger/get-question.swagger.ts
  apps/server/src/questions/swagger/toggle-question.swagger.ts
  apps/server/src/questions/swagger/update-question.swagger.ts
  apps/server/src/replies/dto/toggle-reply-like.dto.ts
  apps/server/src/replies/guards/reply-existence.guard.ts
  apps/server/src/replies/replies.controller.ts
  apps/server/src/replies/replies.module.ts
  apps/server/src/replies/replies.repository.ts
  apps/server/src/replies/replies.service.ts
  apps/server/src/replies/swagger/create-reply.swagger.ts
  apps/server/src/replies/swagger/delete-reply.swagger.ts
  apps/server/src/replies/swagger/toggle-reply.swagger.ts
  apps/server/src/replies/swagger/update-reply.swagger.ts
  apps/server/src/sessions-auth/sessions-auth.controller.ts
  apps/server/src/sessions-auth/sessions-auth.module.ts
  apps/server/src/sessions-auth/sessions-auth.repository.ts
  apps/server/src/sessions-auth/swagger/sessions-auth.swagger.ts
  apps/server/src/sessions/sessions.controller.ts
  apps/server/src/sessions/sessions.module.ts
  apps/server/src/sessions/swagger/create-session.swagger.ts
  apps/server/src/sessions/swagger/get-session.swagger.ts
  apps/server/src/upload/swagger/upload-image.swagger.ts
  apps/server/src/users/exceptions/user.exception.ts
  apps/server/src/users/swagger/check-duplication.swagger.ts
  apps/server/src/users/swagger/create-user.swagger.ts
  apps/server/src/users/users.controller.ts
  apps/server/src/users/users.module.ts
  apps/server/src/users/users.repository.ts
  apps/server/src/users/users.service.ts
  apps/server/tsconfig.json
Labels: Refactor

#117 refactor(be): adjust swagger, return format and validation logic
  apps/server/prisma/schema.prisma
  apps/server/src/auth/auth.controller.ts
  apps/server/src/auth/auth.service.ts
  apps/server/src/auth/swagger/login.swagger.ts
  apps/server/src/common/base.dto.ts
  apps/server/src/common/guards/session-token-validation.guard.ts
  apps/server/src/questions/dto/get-question.dto.ts
  apps/server/src/questions/dto/toggle-question-like.dto.ts
  apps/server/src/questions/guards/question-existence.guard.ts
  apps/server/src/questions/guards/question-ownership.guard.ts
  apps/server/src/questions/questions.controller.ts
  apps/server/src/questions/questions.module.ts
  apps/server/src/questions/questions.repository.ts
  apps/server/src/questions/questions.service.ts
  apps/server/src/questions/swagger/create-question.swagger.ts
  apps/server/src/questions/swagger/delete-question.swagger.ts
  apps/server/src/questions/swagger/get-question.swagger.ts
  apps/server/src/questions/swagger/toggle-question.swagger.ts
  apps/server/src/questions/swagger/update-question.swagger.ts
  apps/server/src/replies/dto/create-reply.dto.ts
  apps/server/src/replies/dto/delete-reply.dto.ts
  apps/server/src/replies/dto/update-reply.dto.ts
  apps/server/src/replies/guards/reply-existence.guard.ts
  apps/server/src/replies/guards/reply-ownership.guard.ts
  apps/server/src/replies/replies.controller.ts
  apps/server/src/replies/replies.repository.ts
  apps/server/src/replies/replies.service.ts
  apps/server/src/replies/swagger/create-reply.swagger.ts
  apps/server/src/replies/swagger/toggle-reply.swagger.ts
  apps/server/src/replies/swagger/update-reply.swagger.ts
  apps/server/src/sessions-auth/dto/session-auth.dto.ts
  apps/server/src/sessions-auth/sessions-auth.controller.ts
  apps/server/src/sessions-auth/sessions-auth.repository.ts
  apps/server/src/sessions-auth/sessions-auth.service.ts
  apps/server/src/sessions/dto/create-session.dto.ts
  apps/server/src/sessions/interface/session-create-data.interface.ts
  apps/server/src/sessions/sessions.controller.ts
  apps/server/src/sessions/sessions.repository.ts
  apps/server/src/sessions/sessions.service.ts
  apps/server/src/sessions/swagger/get-session.swagger.ts
Labels: Refactor

#118 fix(be): reply create exception
  apps/server/src/questions/guards/question-existence.guard.ts
  apps/server/src/questions/questions.controller.ts
  apps/server/src/questions/questions.module.ts
  apps/server/src/questions/questions.repository.ts
  apps/server/src/replies/dto/create-reply.dto.ts
  apps/server/src/replies/replies.controller.ts
  apps/server/src/replies/replies.module.ts
  apps/server/src/replies/replies.repository.ts
  apps/server/src/replies/replies.service.ts
  apps/server/src/replies/swagger/toggle-reply.swagger.ts
  apps/server/src/sessions-auth/sessions-auth.controller.ts
  apps/server/src/sessions/interface/session-create-data.interface.ts
  apps/server/src/sessions/sessions.controller.ts
  apps/server/src/sessions/sessions.service.ts
  apps/server/src/users/users.repository.ts
Labels: Fix

#119 fix(be): fix question delete bug and add reply soft delete
  apps/server/prisma/migrations/20241119020525_add_cascade_delete/migration.sql
  apps/server/prisma/migrations/20241119021515_add_reply_soft_delete/migration.sql
  apps/server/prisma/schema.prisma
  apps/server/src/questions/questions.service.ts
  apps/server/src/questions/swagger/get-question.swagger.ts
  apps/server/src/replies/replies.repository.ts
  apps/server/src/replies/replies.service.ts
  apps/server/src/replies/swagger/create-reply.swagger.ts
  apps/server/src/replies/swagger/delete-reply.swagger.ts
  apps/server/src/replies/swagger/update-reply.swagger.ts
Labels: Fix

#120 fix(be): fix question, reply order bug
  apps/server/src/questions/questions.repository.ts
Labels: Fix

#126 feat(fe): integrate qa api
  apps/client/src/components/modal/CreateQuestionModal.tsx
  apps/client/src/components/modal/CreateReplyModal.tsx
  apps/client/src/components/modal/CreateSessionModal.tsx
  apps/client/src/components/modal/SignUpModal.tsx
  apps/client/src/components/my/SessionRecord.tsx
  apps/client/src/components/qna/Question.tsx
  apps/client/src/components/qna/QuestionContent.tsx
  apps/client/src/components/qna/QuestionDetail.tsx
  apps/client/src/components/qna/QuestionItem.tsx
  apps/client/src/components/qna/QuestionList.tsx
  apps/client/src/components/qna/Reply.tsx
  apps/client/src/components/qna/ReplyItem.tsx
  apps/client/src/features/auth/auth.api.ts
  apps/client/src/features/auth/auth.dto.ts
  apps/client/src/features/auth/auth.hook.ts
  apps/client/src/features/auth/auth.store.ts
  apps/client/src/features/session/qna/index.ts
  apps/client/src/features/session/qna/qna.api.ts
  apps/client/src/features/session/qna/qna.context.tsx
  apps/client/src/features/session/qna/qna.dto.ts
  apps/client/src/features/session/qna/qna.slice.ts
  apps/client/src/features/session/qna/qna.type.ts
  apps/client/src/features/session/session.api.ts
  apps/client/src/features/session/session.dto.ts
  apps/client/src/features/session/session.slice.ts
  apps/client/src/features/session/session.type.ts
  apps/client/src/features/user/user.api.ts
  apps/client/src/features/user/user.dto.ts
  apps/client/src/features/user/user.hook.ts
  apps/client/src/index.css
  apps/client/src/pages/MyPage.tsx
  apps/client/src/pages/QnAPage.tsx
  apps/client/src/routes/__root.tsx
  apps/client/src/routes/index.tsx
  apps/client/src/routes/my.tsx
  apps/client/src/routes/session.$sessionId.tsx
  apps/client/src/shared/base.dto.ts
  apps/client/src/shared/index.ts
Labels: Feature

#128 feat(fe): add toast feedback
  apps/client/src/components/modal/CreateQuestionModal.tsx
  apps/client/src/components/modal/CreateReplyModal.tsx
  apps/client/src/components/qna/QuestionItem.tsx
  apps/client/src/components/qna/ReplyItem.tsx
  apps/client/src/features/auth/auth.hook.ts
  apps/client/src/routes/session.$sessionId.tsx
Labels: Feature

#129 fix(fe): update rendering logic and handle session token retrieval error
  apps/client/src/components/qna/QuestionList.tsx
  apps/client/src/routes/session.$sessionId.tsx
Labels: Fix

#132 fix(fe): apply like toggle API response
  apps/client/src/components/qna/QuestionItem.tsx
  apps/client/src/components/qna/ReplyItem.tsx
Labels: Fix

#137 feat(fe): implement togglable question sections with expand/collapse animations
  apps/client/package.json
  apps/client/src/components/qna/QuestionDivider.tsx
  apps/client/src/components/qna/QuestionList.tsx
  apps/client/src/components/qna/QuestionSection.tsx
  pnpm-lock.yaml
Labels: Feature

#139 refactor(be): add session title in response
  apps/server/src/questions/questions.controller.ts
  apps/server/src/questions/questions.service.ts
  apps/server/src/questions/swagger/get-question.swagger.ts
Labels: Refactor

#141 feat(fe): UI/UX improvement
  apps/client/package.json
  apps/client/src/components/FeatureCard.tsx
  apps/client/src/components/qna/QuestionDetail.tsx
  apps/client/src/components/qna/QuestionDivider.tsx
  apps/client/src/components/qna/QuestionItem.tsx
  apps/client/src/components/qna/QuestionList.tsx
  apps/client/src/components/qna/ReplyItem.tsx
  apps/client/src/features/session/qna/qna.dto.ts
  apps/client/src/features/session/session.slice.ts
  apps/client/src/pages/HomePage.tsx
  apps/client/src/routes/session.$sessionId.tsx
  pnpm-lock.yaml
Labels: Feature

#143 chore(be): path alias eslint
  apps/server/.eslintrc.js
Labels: Style

#144 feat(be): add socketIO
  apps/server/package.json
  apps/server/src/app.module.ts
  apps/server/src/main.ts
  apps/server/src/questions/questions.controller.ts
  apps/server/src/questions/questions.module.ts
  apps/server/src/replies/replies.controller.ts
  apps/server/src/replies/replies.module.ts
  apps/server/src/socket/socket.gateway.ts
  apps/server/src/socket/socket.module.ts
  apps/server/tsconfig.json
  pnpm-lock.yaml
Labels: Feature

#147 fix(be): socket exception handling
  apps/server/src/socket/socket.gateway.ts
Labels: Fix

#150 refactor(be): add question id in reply broadcast messsage
  apps/server/src/replies/replies.controller.ts
  apps/server/src/replies/replies.repository.ts
  apps/server/src/replies/replies.service.ts
Labels: Refactor

#151 feat(fe): implement SocketService for real-time event handling
  apps/client/package.json
  apps/client/src/features/session/qna/qna.type.ts
  apps/client/src/features/socket/index.ts
  apps/client/src/features/socket/socket.service.ts
  apps/client/src/features/socket/socket.type.ts
  apps/client/src/routes/session/route.tsx
  apps/client/src/vite-env.d.ts
  pnpm-lock.yaml
Labels: Feature

#153 fix(be): reply broadcast message 'isOwner' bug
  apps/server/src/replies/replies.controller.ts
Labels: Fix

#152 feat(be): chatting
  apps/server/src/app.module.ts
  apps/server/src/chats/chats.module.ts
  apps/server/src/chats/chats.repository.ts
  apps/server/src/chats/chats.service.ts
  apps/server/src/socket/socket.gateway.ts
  apps/server/src/socket/socket.module.ts
  apps/server/tsconfig.json
Labels: Feature

#155 feat(be): forbid multi access
  apps/server/src/socket/socket.gateway.ts
Labels: Refactor

#156 feat(be): change multi page access policy
  apps/server/src/socket/socket.gateway.ts
Labels: Fix

#157 fix(be): custom message
  apps/server/src/app.module.ts
  apps/server/src/socket/socket.gateway.ts
Labels: Fix

#158 feat(fe): implement socket-based chat messaging system
  apps/client/package.json
  apps/client/src/components/qna/ChattingList.tsx
  apps/client/src/components/qna/ChattingMessage.tsx
  apps/client/src/components/qna/QuestionDetail.tsx
  apps/client/src/components/qna/QuestionDivider.tsx
  apps/client/src/components/qna/QuestionList.tsx
  apps/client/src/components/qna/QuestionSection.tsx
  apps/client/src/features/session/chatting/chatting.type.ts
  apps/client/src/features/socket/index.ts
  apps/client/src/features/socket/socket.context.tsx
  apps/client/src/features/socket/socket.hook.ts
  apps/client/src/features/socket/socket.service.ts
  apps/client/src/features/socket/socket.type.ts
  apps/client/src/routes/session/route.tsx
  apps/client/tailwind.config.js
  pnpm-lock.yaml
Labels: Feature

#159 fix(fe): remove unused properties and adjust modal heights
  apps/client/src/components/modal/CreateQuestionModal.tsx
  apps/client/src/components/modal/CreateReplyModal.tsx
  apps/client/src/components/qna/ChattingList.tsx
  apps/client/src/features/socket/socket.service.ts
Labels: Fix

#162 feat(fe): UX improvements
  apps/client/src/components/modal/CreateSessionModal.tsx
  apps/client/src/components/qna/ChattingList.tsx
Labels: Feature

#163 feat(fe): add Safari browser support for scrollend event
  apps/client/src/components/qna/ChattingList.tsx
Labels: Feature, Fix

#170 feat(be): set http logger and connection logger
  apps/server/package.json
  apps/server/src/app.module.ts
  apps/server/src/common/filters/global-exception.filter.ts
  apps/server/src/common/filters/http-exception.filter.ts
  apps/server/src/common/middlewares/http-logger.middleware.ts
  apps/server/src/logger/logger.module.ts
  apps/server/src/logger/logger.service.ts
  apps/server/src/logger/winston.config.ts
  apps/server/src/main.ts
  apps/server/src/socket/socket.gateway.ts
  apps/server/src/socket/socket.module.ts
  apps/server/tsconfig.json
  pnpm-lock.yaml
Labels: Feature

#172 feat(be): add socket event that broadcasts participants count in session
  apps/server/package.json
  apps/server/src/socket/socket.gateway.ts
  pnpm-lock.yaml
Labels: Feature

#175 fix(be): rename callback parameter in hasNickname from 'nickname' to 'user'
  apps/server/package.json
  apps/server/src/users/users.service.ts
  pnpm-lock.yaml
Labels: Fix

#177 fix(be): add user validation DTO
  apps/server/src/users/dto/check-email.dto.ts
  apps/server/src/users/dto/check-nickname.dto.ts
  apps/server/src/users/users.controller.ts
Labels: Fix

#179 fix(fe): improve user scroll handling logic in chatting
  apps/client/src/components/qna/ChattingList.tsx
  apps/client/src/components/qna/ReplyItem.tsx
  apps/client/src/features/user/user.api.ts
Labels: Fix

#180 fix(fe): update session name validation rules
  apps/client/src/components/modal/CreateSessionModal.tsx
Labels: Fix

#181 fix(fe): adjust button order
  apps/client/src/components/modal/CreateQuestionModal.tsx
  apps/client/src/components/modal/CreateReplyModal.tsx
  apps/client/src/components/modal/CreateSessionModal.tsx
  apps/client/src/components/modal/SignInModal.tsx
  apps/client/src/components/modal/SignUpModal.tsx
Labels: Fix

#185 feat(be): multi host
  apps/server/prisma/migrations/20241126054534_init/migration.sql
  apps/server/prisma/migrations/20241126060448_add_is_host_mapping/migration.sql
  apps/server/prisma/schema.prisma
  apps/server/src/questions/questions.service.ts
  apps/server/src/replies/replies.controller.ts
  apps/server/src/replies/replies.service.ts
  apps/server/src/sessions-auth/dto/update-host.dto.ts
  apps/server/src/sessions-auth/sessions-auth.controller.ts
  apps/server/src/sessions-auth/sessions-auth.module.ts
  apps/server/src/sessions-auth/sessions-auth.repository.ts
  apps/server/src/sessions-auth/sessions-auth.service.ts
  apps/server/src/sessions-auth/swagger/sessions-host.swagger.ts
  apps/server/src/sessions-auth/swagger/sessions-user.swagger.ts
  apps/server/src/sessions/sessions.module.ts
  apps/server/src/sessions/sessions.repository.ts
  apps/server/src/sessions/sessions.service.ts
  pnpm-lock.yaml
Labels: Feature

#182 feat(fe): prevent duplicate api requests
  apps/client/src/components/modal/CreateQuestionModal.tsx
  apps/client/src/components/modal/CreateReplyModal.tsx
  apps/client/src/components/modal/CreateSessionModal.tsx
  apps/client/src/components/modal/SignInModal.tsx
  apps/client/src/components/modal/SignUpModal.tsx
  apps/client/src/components/qna/QuestionItem.tsx
  apps/client/src/components/qna/ReplyItem.tsx
  apps/client/src/features/auth/auth.hook.ts
Labels: Feature

#184 fix(fe): simplify ToastMessage component
  apps/client/src/features/toast/ToastMessage.tsx
Labels: Fix

#187 feat(fe): implement multi-host ui
  apps/client/src/components/index.ts
  apps/client/src/components/modal/Participant.tsx
  apps/client/src/components/modal/SessionParticipantsModal.tsx
  apps/client/src/components/qna/ChattingList.tsx
  apps/client/src/features/toast/ToastContainer.tsx
  apps/client/src/features/toast/ToastMessage.tsx
Labels: Feature

#192 fix(be): correct 'refreshtToken' typo
  apps/server/src/auth/auth.controller.ts
Labels: Fix

#191 feat(fe): custom scroll bar
  apps/client/src/components/qna/ChattingList.tsx
  apps/client/src/components/qna/QuestionDetail.tsx
  apps/client/src/components/qna/QuestionList.tsx
  apps/client/src/index.css
  apps/client/src/pages/MyPage.tsx
Labels: Feature

#189 feat(fe): add favicon and update header styling with new font
  apps/client/index.html
  apps/client/public/ask-it.svg
  apps/client/src/components/Header.tsx
  apps/client/src/index.css
  apps/client/tailwind.config.js
Labels: Feature

#194 feat(be): add multi host broadcasting
  apps/server/src/auth/auth.controller.ts
  apps/server/src/auth/swagger/login.swagger.ts
  apps/server/src/questions/dto/get-question.dto.ts
  apps/server/src/questions/questions.repository.ts
  apps/server/src/questions/questions.service.ts
  apps/server/src/questions/swagger/get-question.swagger.ts
  apps/server/src/replies/replies.repository.ts
  apps/server/src/replies/replies.service.ts
  apps/server/src/replies/swagger/create-reply.swagger.ts
  apps/server/src/sessions-auth/dto/update-host.dto.ts
  apps/server/src/sessions-auth/sessions-auth.controller.ts
  apps/server/src/sessions-auth/sessions-auth.module.ts
  apps/server/src/socket/socket.gateway.ts
Labels: Feature

#195 refactor(be): add userId in refresh token response
  apps/server/src/auth/auth.controller.ts
  apps/server/src/auth/auth.service.ts
  apps/server/src/auth/swagger/login.swagger.ts
Labels: Refactor

#196 fix(be): host validation
  apps/server/src/questions/questions.service.ts
Labels: Fix

#201 fix(fe): modify validation logic for signup process
  apps/client/src/components/Button.tsx
  apps/client/src/components/qna/QuestionList.tsx
  apps/client/src/components/qna/SessionSettingsDropdown.tsx
  apps/client/src/features/user/user.api.ts
  apps/client/src/features/user/user.hook.ts
  apps/client/src/shared/validation/validation-status.util.ts
Labels: Fix

#202 feat(fe): add session sharing
  apps/client/src/components/modal/CreateSessionModal.tsx
  apps/client/src/components/modal/SignInModal.tsx
  apps/client/src/components/modal/SignUpModal.tsx
  apps/client/src/components/qna/QuestionList.tsx
Labels: Feature

#205 fix(fe): prevent invalid routing
  apps/client/.eslintrc.json
  apps/client/src/components/Button.tsx
  apps/client/src/routes/my.tsx
  apps/client/src/routes/session/$sessionId/$questionId/index.tsx
  apps/client/src/routes/session/$sessionId/index.tsx
  apps/client/src/routes/session/route.tsx
Labels: Fix

#207 feat(fe): add zod library for request/response/socket-payload validation
  apps/client/package.json
  apps/client/src/features/auth/auth.dto.ts
  apps/client/src/features/session/qna/qna.dto.ts
  apps/client/src/features/session/qna/qna.type.ts
  apps/client/src/features/session/session.dto.ts
  apps/client/src/features/session/session.type.ts
  apps/client/src/features/socket/socket.service.ts
  apps/client/src/features/socket/socket.type.ts
  apps/client/src/features/user/user.dto.ts
  pnpm-lock.yaml
Labels: Feature

#208 feat(be): chatting list
  apps/server/src/chats/chats.controller.ts
  apps/server/src/chats/chats.module.ts
  apps/server/src/chats/chats.service.ts
  apps/server/src/chats/swagger/get-chats.swagger.ts
  apps/server/src/questions/questions.service.ts
  apps/server/src/sessions-auth/sessions-auth.service.ts
Labels: Feature

#211 feat(fe): load previous chattings
  apps/client/src/components/qna/ChattingList.tsx
  apps/client/src/features/session/chatting/chatting.api.ts
  apps/client/src/features/session/chatting/chatting.dto.ts
  apps/client/src/features/session/chatting/chatting.slice.ts
  apps/client/src/features/session/chatting/chatting.type.ts
  apps/client/src/features/session/chatting/index.ts
  apps/client/src/routes/session/$sessionId/$questionId/index.tsx
  apps/client/src/routes/session/$sessionId/index.tsx
Labels: Feature

#214 feat(be): add session termination
  apps/server/src/common/guards/session-token-validation.guard.ts
  apps/server/src/sessions/dto/terminate-session.dto.ts
  apps/server/src/sessions/sessions.controller.ts
  apps/server/src/sessions/sessions.module.ts
  apps/server/src/sessions/sessions.repository.ts
  apps/server/src/sessions/sessions.service.ts
  apps/server/src/sessions/swagger/terminate-session.swagger.ts
  apps/server/src/socket/socket.gateway.ts
Labels: Feature

#213 feat(fe): add validation logic using zod
  apps/client/src/components/qna/ChattingList.tsx
  apps/client/src/features/auth/auth.api.ts
  apps/client/src/features/session/chatting/chatting.api.ts
  apps/client/src/features/session/qna/qna.api.ts
  apps/client/src/features/session/qna/qna.type.ts
  apps/client/src/features/session/session.api.ts
  apps/client/src/features/socket/socket.service.ts
  apps/client/src/features/socket/socket.type.ts
  apps/client/src/features/user/user.api.ts
Labels: Feature

#217 fix(fe): include userId in reply addition for CreateReplyModal
  apps/client/src/components/modal/CreateReplyModal.tsx
Labels: Fix

#218 feat(fe): implement session termination
  apps/client/src/components/modal/SessionTerminateModal.tsx
  apps/client/src/components/qna/QuestionList.tsx
  apps/client/src/features/session/session.api.ts
  apps/client/src/features/session/session.dto.ts
  apps/client/src/features/socket/socket.service.ts
Labels: Feature

#219 feat(be): power deletion
  apps/server/prisma/migrations/20241128045519_add_on_delete_cascade_to_reply_question/migration.sql
  apps/server/prisma/schema.prisma
  apps/server/src/questions/questions.controller.ts
  apps/server/src/questions/questions.service.ts
  apps/server/src/replies/replies.controller.ts
  apps/server/src/replies/replies.service.ts
Labels: Feature

#221 feat(fe): add question and reply item delete action for host users
  apps/client/src/components/qna/QuestionItem.tsx
  apps/client/src/components/qna/ReplyItem.tsx
Labels: Feature

#223 feat(fe): change styles
  apps/client/src/components/modal/DeleteConfirmModal.tsx
  apps/client/src/components/qna/QuestionDetail.tsx
  apps/client/src/components/qna/QuestionItem.tsx
  apps/client/src/components/qna/QuestionList.tsx
  apps/client/src/components/qna/ReplyItem.tsx
  apps/client/src/components/qna/SessionSettingsDropdown.tsx
  apps/client/src/features/socket/socket.service.ts
Labels: Feature

#225 docs: update README.md
  README.md
Labels: Documentation

#224 fix(be): sort session history in descending order
  apps/server/src/sessions/sessions.repository.ts
Labels: Fix

#226 fix(fe): apply feedback
  apps/client/src/components/modal/SessionParticipantsModal.tsx
  apps/client/src/features/auth/auth.api.ts
  apps/client/src/features/auth/auth.hook.ts
Labels: Fix

#227 feat(fe): add notification about permission errors
  apps/client/src/components/modal/SessionParticipantsModal.tsx
Labels: Feature, Fix

#228 feat(fe): include question content in reply modal
  apps/client/src/components/modal/CreateQuestionModal.tsx
  apps/client/src/components/modal/CreateReplyModal.tsx
  apps/client/src/components/qna/QuestionList.tsx
Labels: Feature

#229 fix(fe): adjust modal style
  apps/client/src/components/modal/CreateQuestionModal.tsx
  apps/client/src/components/modal/CreateReplyModal.tsx
Labels: Fix, Style
