Repository boostcampwm-2024/web07-Ask-It, pull requests merged in 2024-12, with the labels that each got.

#230 refactor(be): remove unnecessary refresh token check in jwt auth guard
  apps/server/src/auth/auth.service.ts
  apps/server/src/auth/jwt-auth.guard.ts
Labels: Refactor

#231 docs: Update README
  README.md
Labels: Documentation

#232 fix(fe): update axios interceptor
  apps/client/src/shared/axios.config.ts
Labels: Fix

#233 docs: Update README
  README.md
Labels: Documentation

#235 test: add service test with mocking
  apps/server/package.json
  apps/server/src/chats/chats.repository.ts
  apps/server/src/chats/chats.service.spec.ts
  apps/server/src/chats/chats.service.ts
  apps/server/src/questions/questions.service.spec.ts
  apps/server/src/replies/replies.service.spec.ts
  apps/server/src/sessions-auth/sessions-auth.service.spec.ts
  apps/server/src/sessions/sessions.service.spec.ts
Labels: Test

#239 refactor(be): refactoring exception handling logic
  apps/server/src/chats/chats.repository.ts
  apps/server/src/common/exceptions/resource.exception.ts
  apps/server/src/common/guards/session-token-validation.guard.ts
  apps/server/src/questions/questions.repository.ts
  apps/server/src/questions/questions.service.ts
  apps/server/src/replies/replies.repository.ts
  apps/server/src/sessions-auth/sessions-auth.repository.ts
  apps/server/src/sessions/sessions.repository.ts
  apps/server/src/socket/socket.gateway.ts
  apps/server/src/users/users.repository.ts
  apps/server/src/users/users.service.ts
Labels: Refactor

#238 test(fe): add playwright tests
  .github/workflows/test.yml
  apps/client/.eslintrc.json
  apps/client/.gitignore
  apps/client/package.json
  apps/client/playwright.config.ts
  apps/client/src/components/Button.tsx
  apps/client/src/components/modal/SignInModal.tsx
  apps/client/src/components/modal/SignUpModal.tsx
  apps/client/src/routes/session/$sessionId/index.tsx
  apps/client/tests/HomePage.spec.ts
  apps/client/tests/MyPage.spec.ts
  apps/client/tests/QnADetailPage.spec.ts
  apps/client/tests/QnAPage.spec.ts
  apps/client/tsconfig.app.json
  package.json
  pnpm-lock.yaml
  turbo.json
Labels: Feature, Configuration, Test

#240 chore: modify test workflow file
  .github/workflows/test.yml
  apps/server/src/questions/questions.service.spec.ts
  package.json
Labels: Configuration, Test

#242 test(fe): change config file
  apps/client/package.json
  apps/client/playwright.config.ts
  apps/client/tests/QnADetailPage.spec.ts
  apps/client/tests/QnAPage.spec.ts
Labels: Configuration

#244 feat(be): add database index
  apps/server/prisma/migrations/20241203042135_add_session_id_index_in_chatting/migration.sql
  apps/server/prisma/migrations/20241203043418_add_session_id_chatting_id_composite_indexx/migration.sql
  apps/server/prisma/migrations/20241203052414_modify_chatting_index/migration.sql
  apps/server/prisma/migrations/20241203052615_modify_chatting_composite_index_desc/migration.sql
  apps/server/prisma/migrations/20241203053124_add_question_session_id_index/migration.sql
  apps/server/prisma/schema.prisma
Labels: Feature

#245 feat(fe): add Zod error handling
  apps/client/.prettierrc
  apps/client/src/components/Button.tsx
  apps/client/src/components/FeatureCard.tsx
  apps/client/src/components/Header.tsx
  apps/client/src/components/modal/CreateQuestionModal.tsx
  apps/client/src/components/modal/CreateReplyModal.tsx
  apps/client/src/components/modal/CreateSessionModal.tsx
  apps/client/src/components/modal/DeleteConfirmModal.tsx
  apps/client/src/components/modal/InputField.tsx
  apps/client/src/components/modal/Participant.tsx
  apps/client/src/components/modal/SessionParticipantsModal.tsx
  apps/client/src/components/modal/SessionTerminateModal.tsx
  apps/client/src/components/modal/SignInModal.tsx
  apps/client/src/components/modal/SignUpModal.tsx
  apps/client/src/components/my/SessionRecord.tsx
  apps/client/src/components/qna/ChattingList.tsx
  apps/client/src/components/qna/ChattingMessage.tsx
  apps/client/src/components/qna/QuestionDetail.tsx
  apps/client/src/components/qna/QuestionDivider.tsx
  apps/client/src/components/qna/QuestionItem.tsx
  apps/client/src/components/qna/QuestionList.tsx
  apps/client/src/components/qna/QuestionSection.tsx
  apps/client/src/components/qna/ReplyItem.tsx
  apps/client/src/components/qna/SessionSettingsDropdown.tsx
  apps/client/src/features/auth/auth.api.ts
  apps/client/src/features/auth/auth.hook.ts
  apps/client/src/features/auth/auth.store.ts
  apps/client/src/features/auth/validation/index.ts
  apps/client/src/features/auth/validation/validation-status.type.ts
  apps/client/src/features/auth/validation/validation-status.util.ts
  apps/client/src/features/modal/modal.context.ts
  apps/client/src/features/session/chatting/chatting.api.ts
  apps/client/src/features/session/chatting/chatting.dto.ts
  apps/client/src/features/session/chatting/chatting.slice.ts
  apps/client/src/features/session/qna/qna.api.ts
  apps/client/src/features/session/qna/qna.dto.ts
  apps/client/src/features/session/qna/qna.slice.ts
  apps/client/src/features/session/session.api.ts
  apps/client/src/features/session/session.dto.ts
  apps/client/src/features/session/session.slice.ts
  apps/client/src/features/session/session.store.ts
  apps/client/src/features/socket/socket.context.tsx
  apps/client/src/features/socket/socket.service.ts
  apps/client/src/features/socket/socket.type.ts
  apps/client/src/features/toast/toast.store.ts
  apps/client/src/features/user/user.api.ts
  apps/client/src/features/user/user.dto.ts
  apps/client/src/features/user/user.hook.ts
  apps/client/src/pages/HomePage.tsx
  apps/client/src/routeTree.gen.ts
  apps/client/src/routes/session/$sessionId/$questionId/index.tsx
  apps/client/src/routes/session/route.tsx
  apps/client/src/shared/axios.config.ts
  apps/client/src/shared/index.ts
  apps/client/tailwind.config.js
  apps/client/tests/HomePage.spec.ts
  apps/client/tests/QnADetailPage.spec.ts
  apps/client/tests/QnAPage.spec.ts
  apps/client/tsconfig.json
Labels: Feature

#246 feat(fe): add toggle for hiding expired sessions
  apps/client/src/components/my/SessionRecord.tsx
  apps/client/src/components/qna/ChattingList.tsx
  apps/client/src/components/qna/QuestionList.tsx
  apps/client/src/pages/MyPage.tsx
  apps/client/tests/MyPage.spec.ts
  apps/client/tests/QnAPage.spec.ts
Labels: Feature

#248 test(fe): remove logout flow in login/logout flow test to focus on login process
  apps/client/src/features/auth/auth.api.ts
  apps/client/src/routes/session/$sessionId/index.tsx
  apps/client/tests/HomePage.spec.ts
Labels: Fix, Test

#250 feat(be): separate socket server
  .github/workflows/deploy.yml
  apps/server/ecosystem.config.js
  apps/server/src/common/request-socket.ts
  apps/server/src/main.ts
  apps/server/src/questions/questions.controller.ts
  apps/server/src/questions/questions.module.ts
  apps/server/src/replies/replies.controller.ts
  apps/server/src/replies/replies.module.ts
  apps/server/src/sessions-auth/sessions-auth.controller.ts
  apps/server/src/sessions-auth/sessions-auth.module.ts
  apps/server/src/sessions/sessions.controller.ts
  apps/server/src/sessions/sessions.module.ts
  apps/server/src/socket/dto/broadcast-event.dto.ts
  apps/server/src/socket/socket.constant.ts
  apps/server/src/socket/socket.controller.ts
  apps/server/src/socket/socket.gateway.ts
  apps/server/src/socket/socket.module.ts
Labels: Feature

#251 fix: update deploy.yml
  .github/workflows/deploy.yml
Labels: Fix

#252 fix: modify pm2 script
  apps/server/ecosystem.config.js
  apps/server/package.json
Labels: Fix

#253 Update README.md
  README.md
Labels: Documentation
